### ISSUE TITLE
bug: Reduced performence on multi-cores by thread-safe glibc/rand implementations

### ISSUE THREAD

**Issue by SebastianNiemann** [SebastianNiemann/Mantella#204]
As noted by @wlfbck the performance of parallel loops gets worse on some multi-core systems, where glibc uses a thread-safe random implementation (see http://stackoverflow.com/questions/8980056/splitting-up-a-program-into-4-threads-is-slower-than-a-single-thread)

**Without OpenMP:**
```
Performance counter stats for '../../../a.out':

      15629.384308 task-clock                #    1.022 CPUs utilized
                82 context-switches          #    0.005 K/sec
                 6 cpu-migrations            #    0.000 K/sec
               889 page-faults               #    0.057 K/sec
    43,221,175,564 cycles                    #    2.765 GHz
    26,068,680,890 stalled-cycles-frontend   #   60.31% frontend cycles idle
    13,828,925,903 stalled-cycles-backend    #   32.00% backend  cycles idle
    36,899,597,727 instructions              #    0.85  insns per cycle
                                             #    0.71  stalled cycles per insn
    11,085,697,728 branches                  #  709.286 M/sec
        54,116,945 branch-misses             #    0.49% of all branches

      15.287802356 seconds time elapsed
```

**With OpenMP:**
```
Performance counter stats for '../../../a.out':

      11637.811356 task-clock                #    2.962 CPUs utilized
           813,775 context-switches          #    0.070 M/sec
                68 cpu-migrations            #    0.006 K/sec
               881 page-faults               #    0.076 K/sec
    29,185,307,650 cycles                    #    2.508 GHz
    19,867,143,186 stalled-cycles-frontend   #   68.07% frontend cycles idle
    15,606,353,341 stalled-cycles-backend    #   53.47% backend  cycles idle
    13,384,377,491 instructions              #    0.46  insns per cycle
                                             #    1.48  stalled cycles per insn
     3,039,017,071 branches                  #  261.133 M/sec
        21,019,502 branch-misses             #    0.69% of all branches

       3.928415902 seconds time elapsed
```
Note the high amount of context-switches.

**Comment by SebastianNiemann** [comment]
The solution to this problem is based on replacing all `arma::rand[u,n,i](...)` calls with our own ones, which instantiate one random number generator per thread. This will also affect calls like `std::uniform_real_distribution(..)`.

Since we now need to know the number of maximal thread and the current thread number, it would be best to provide this by a function `config.hpp`, handling OpenMP-Support at a central place. We should then also provide the node rank and number of nodes by similar functions.

@wlfbck I try to add the latter part regarding the function under `config.hpp` this night.

**Comment by wlfbck** [comment]
first version is up. Please check if the template style is appropriate (it's similar to Armadillos fn_randu/n/i.hpp). I omitted arma::Cube cause it wasn't used anywhere.

Armadillo is doing some mem-magic when filling vectors and matrices (see arma_rng.hpp), not sure if it makes sense to do something similar (besides the fact that i wouldn't know how to do it, yet) or if the compiler takes care of it anyway.
