### ISSUE TITLE
Bug: CMakeLists.txt: Mantella is not build with shared libraries

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#210]
Currently, one gets linker errors if Mantella and Armadillo are installed the usual way: http://pastebin.com/2yQDzsZe

The equivalent of `-DBUILD_SHARED_LIBS=ON` needs to be added to CMakeLists.txt again to fix this problem.

**Comment by wlfbck** [comment]
`set(LIBRARY_TYPE SHARED)
if(WIN32)
  set(LIBRARY_TYPE STATIC)
endif()

# All paths must start with "src/"
add_library(mantella ${LIBRARY_TYPE}`

seems to work as a fix. (at roughly line 113)

**Comment by SebastianNiemann** [comment]
The problem seems to be on CMake's side, as ` find_library` does not care whether we want to create a shared or static library and favors finding shared ones.

The easiest solution would be to specify Mantella once again as a shared library
