### ISSUE TITLE
README.md suggestions

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#48]
* Logopicture should either lead to mantella.info or not be clickable
 * Occurrences of Mantella in text should be links
 * There is no hint that the *detailled* API can be found under mantella.info

**Comment by SebastianNiemann** [comment]
Thank you, everything done by ad5f986bb1193531a1e658088397defad70857d4 and 5867ff937862af4b1ac19778354a6b95292678d4.
