### ISSUE TITLE
HookeJeeves Fatal Bug

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#80]
HookeJeeves uses bestParameter, which on the first iteration is `[matrix size: 0x1]` thus `arma::Col<double> nextParameterCandidate = bestParameter_;
nextParameterCandidate(n) += stepSize_;`
fails. I guess `bestParameter_ = initialParameter_;` from the old version should be in optimise() of HookeJeeves, but not sure.

**Comment by wlfbck** [comment]
I just noticed a similar problem affects HillClimbing, since bestParameter_ is never set but used.

**Comment by SebastianNiemann** [comment]
This was already fixed in an old commit from a long long long time ago
