### ISSUE TITLE
bestObjectiveValue and difference calcuation

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#81]
Currently the difference gets calculated as
`const double difference = bestObjectiveValue_ - objectiveValue;`
which, since bestObjectiveValue is infinite at start, will result in difference also being infinite.

So checking for `if (difference < 0) {` will never find a better bestParameter. Since we presumably want to minimize the objectivevalue the arguments for difference should be switched. This will still return -infinity for the first iteration though, and might be a problem for some algorithms?

**Comment by SebastianNiemann** [comment]
This was fixed within the *functional* branch by b3e779a2f8ea784f55ef77b9dd78f4aa37682787
