### ISSUE TITLE
acceptableObjectiveValue

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#82]
Another problem i noticed is that acceptableObjectiveValue is never automatically set (which i realise is intentional afaik), but it might be nice to do it automatically for atleast the bbob ones.
Or even have a base class for all problems which are able to provide an acceptable value, for which the value is automatically set.

**Comment by SebastianNiemann** [comment]
Done by 3751b33a9572c94112341b3f21f60a88f035de98 and #58
