### ISSUE TITLE
BBOB Problems

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#83]
It would be helpful to have the number and complete name as used in the original bbob files as a comment in the header files, cause the current class names are quite different.

**Comment by SebastianNiemann** [comment]
Could you give me an example? The problems should be named excatly as in http://coco.lri.fr/downloads/download15.02/bbobdocfunctionsdef.pdf

**Comment by wlfbck** [comment]
Mhm interesting, i was referring to the names which they gave out in benchmarks.m (i listed them all in cmaes3.55-branch under Matlabtest/bbob.m)

Some of them are different (to non-mathematicians), i'm not sure which is which for these:
`separable ellipsoid with monotone transformation, condition 1e6` or `ellipsoid with monotone transformation, condition 1e6`  vs `EllipsoidalFunction` or `EllipsoidalFunctionRotated`
`Rastrigin with monotone transformation separable "condition" 10` or `Rastrigin with asymmetric non-linear distortion, "condition" 10` vs `RastriginFunction` or `RastriginFunctionRotated`

**Comment by wlfbck** [comment]
Forgot to say: The function number is helpful to know if the name isnt present in matlab or in the result pdfs from the bbob-website.

**Comment by SebastianNiemann** [comment]
These BBOB Matlab files never fail to irritate me ...

Looking at the math, I got the following conversion table:

Matlab handle | Commented name | Mantella class
--------------|----------------|----------------
f1 | sphere function | mant::bbob::SphereFunction
f2 | separable ellipsoid with monotone transformation, condition 1e6 | mant::bbob::EllipsoidalFunction
f3 | Rastrigin with monotone transformation separable "condition" 10 | mant::bbob::RastriginFunction
f4 | skew Rastrigin-Bueche, condition 10, skew-"condition" 100 | mant::bbob::BuecheRastriginFunction 
f5 | linear slope | mant::bbob::LinearSlope
f6 | attractive sector function | mant::bbob::AttractiveSectorFunction
f7 | step-ellipsoid, condition 100 | mant::bbob::StepEllipsoidalFunction
f8 | Rosenbrock, non-rotated | mant::bbob::RosenbrockFunction
f9 | Rosenbrock, rotated | mant::bbob::RosenbrockFunctionRotated
f10 | ellipsoid with monotone transformation, condition 1e6 | mant::bbob::EllipsoidalFunctionRotated
f11 | discus (tablet) with monotone transformation, condition 1e6 | mant::bbob::DiscusFunction
f12 | bent cigar with asymmetric space distortion, condition 1e6 | mant::bbob::BentCigarFunction
f13 | sharp ridge | mant::bbob::SharpRidge
f14 | sum of different powers, between x^2 and x^6 | mant::bbob::DifferentPowersFunction
f15 | Rastrigin with asymmetric non-linear distortion, "condition" 10 | mant::bbob::RastriginFunctionRotated
f16 | Weierstrass, condition 100 | mant::bbob::WeierstrassFunction
f17 | Schaffers F7 with asymmetric non-linear transformation, condition 10 | mant::bbob::SchaffersF7Function
f18 | Schaffers F7 with asymmetric non-linear transformation, condition 1000 | mant::bbob::SchaffersF7FunctionIllConditioned
f19 | F8F2 sum of Griewank-Rosenbrock 2-D blocks | mant::bbob::CompositeGriewankRosenbrockFunctionF8F2
f20 | Schwefel with tridiagonal variable transformation | mant::bbob::SchwefelFunction
f21 | Gallagher with 101 Gaussian peaks, condition up to 1000, one global rotation | mant::bbob::GallaghersGaussian101mePeaksFunction
f22 | Gallagher with 21 Gaussian peaks, condition up to 1000, one global rotation | mant::bbob::GallaghersGaussian21hiPeaksFunction
f23 | Katsuura function | mant::bbob::KatsuuraFunction
f24 | Lunacek bi-Rastrigin, condition 100 | mant::bbob::LunacekBiRastriginFunction
